### ISSUE TITLE
Duda con enunciado respecto a usuarios

### ISSUE THREAD

**Issue by masotog1997** [IIC3103-2024-02/help#1]
Hola

Tengo las siguientes dudas con el enunciado:
- El enunciado menciona que los usuarios pueden encontrarse en uno de los siguientes cuatro estados: esperando afuera del ascensor, solicitado afuera del ascensor, esperando adentro del ascensor:, solicitado adentro del ascensor, pero en el enunciado en la descripción de los modelos dice: "status": string, ("waiting" | "requested"). No deberían ser 4 los status posibles? Está bien si le puse: waiting_outside, requested_outside, waiting_inside, requested_inside??
- También sobre los usuarios, en la creación de uno nuevo dice: Método HTTP y Ruta POST /users, Request Body {"weight": int, "level_id": int}. Pero no debiese ser aquí acorde al modelo que también describe el enunciado? (vale decir { "id": string, "destination": int, weight": int, "status": string, ("waiting" | "requested") (o los 4 status correspondientes) }

Gracias

**Comment by Francescorodriguezg** [comment]
Hola! 
Con respecto al punto 1, esperando = waiting y solicitado = requested. Los estados 1 y 3 empiezan con "esperando", por ende el status correspondiente es waiting en ambos casos, lo mismo para los estados 2 y 4 que empiezan con "solicitado", su status correspondiente es requested.

Respecto al punto dos, al momento de crear un usuario solo necesitas saber en qué piso lo crearás y cuanto pesa. Los otros campos los puedes inicializar en 0 o como desees.

Quedo atento si tienes otras consultas

Slds

**Comment by masotog1997** [comment]
Hola!
Sobre el 1) Ok entiendo! Entonces serían solo 2 status pero 4 estados de usuario? Igual el que es atributo del usuario sería solo status verdad? (y los que aparecen en el enunciado)
Sobre el pto 2) Entiendo, es necesario agregar como atributo el nivel en que se encuentra el usuario o eso tiene relación con el Level mejor dicho?

Saludos!

**Comment by Francescorodriguezg** [comment]
Hola
Perdona pero me cuesta entender la primera pregunta. Te detallo un poco más:
1) Efectivamente se usa waiting como status indistintamente para el estado 1 y 3 que se describe en el enunciado, lo mismo con requested para los estados 2 y 4. Basta con que tengas status como atributo de usuario, y que te asegures que si se está esperando afuera del ascensor o esperando adentro del ascensor el status diga waiting (análogo para requested).
2) El level que te dan al crear el usuario es para que puedas agregarlo a la lista de usuarios de ese level id.

**Comment by dedarritchon** [comment]
Hola @masotog1997 ,

Intentando aclarar la duda, los "estados", la modelación de los estados queda a criterio del desarrollador.

En ese sentido, se podría tener un identificador para cada estado literalmente, por ejemplo:

- waiting_outside
- requested_outside
- waiting_inside
- requested_inside

o por otro lado se podría tener 2 estados:

- waiting
- requested

y distinguir los 4 estados según la ubicación del usuario (si el usuario está en estado `waiting` y está en el piso, sería equivalente a `waiting_outside`).

Ambas modelaciones están permitidas ya que no se revisará literalmente el nombre del estado que usen en las respuestas.

Respecto a la creación del usuario, dado que siempre se crean en el piso, siempre deben partir en estado waiting en el piso, es decir `waiting_outside` o simplemente `waiting`.

Saludos,
Daniel

**Comment by masotog1997** [comment]
Hola, muchas gracias por la aclaración!!

Saludos,
Marcela
