### ISSUE TITLE
Error test case 1

### ISSUE THREAD

**Issue by VicenteSaldana** [IIC3103-2024-02/help#10]
Estoy teniendo el siguiente error:

Running test: case_1... Test Failed: {"reason": "Expected 400, got 200. incorrect level (should go to 20)", "request": {"method": "PATCH", "url": "http://host.docker.internal:8000/elevators/12f08300-f794-4b50-af7f-a8c7d5278f18", "body": {"level": 20}}, "response": {"status": 200, "body": {"id": "12f08300-f794-4b50-af7f-a8c7d5278f18", "level": {"id": 20, "users": [{"id": "99f60d7e-e819-445a-8d87-b7136ce9e561", "destination": null, "weight": 66, "status": "waiting"}, {"id": "38df4da5-ba79-46d0-a0cd-061389b1764d", "destination": null, "weight": 85, "status": "waiting"}, {"id": "44b55266-0e6f-41dd-bdcb-40f68c83c195", "destination": null, "weight": 84, "status": "waiting"}, {"id": "6181ebbe-7fa0-4064-b80d-636bce7622ae", "destination": null, "weight": 82, "status": "waiting"}, {"id": "0efc0882-c02c-472b-88d4-4e460935be6d", "destination": null, "weight": 71, "status": "waiting"}, {"id": "16665b8e-bafc-433a-9d89-b284ec16e9e8", "destination": null, "weight": 80, "status": "waiting"}, {"id": "36d7ea16-1ab1-4dcd-b973-e4db25df0b53", "destination": null, "weight": 84, "status": "waiting"}]}, "max_weight": 1786, "doors": "closed", "users": []}}, "expected": {"status": 400, "body": {"error": "mensaje de error (no relevante)"}}} (0.289179s)

Entiendo que dice que estoy devolviendo 200 ok, cuando debería entregar error 400. Pero dice: incorrect level (should go to 20) lo cual no tiene sentido porque el body le pide que vaya al nivel 20 y yo lo estoy moviendo al nivel 20. Si me pueden ayudar a entender cuál está siendo el error lo agradecería.

**Comment by dedarritchon** [comment]
Hola @VicenteSaldana ,

El log del error está incorrecto, lo corrijo y comento por acá cuando esté arreglado.

Saludos,
Daniel

**Comment by dedarritchon** [comment]
Hola @VicenteSaldana ,

He actualizado el mensaje de error en el tester. Simplemente necesitas volver a descargar la imagen del tester utilizando `docker pull ....`

En cuanto al caso 1, lo que se está probando es lo siguiente:

- Se crean varios usuarios en un nivel específico.
- Uno de los usuarios solicita un ascensor.
- Se crea un ascensor que sube al nivel para recoger a los usuarios hasta que alcanza su capacidad máxima.
- Los usuarios que no pudieron subir solicitan el ascensor nuevamente.
- Se crea un segundo ascensor que sube para recoger a los usuarios restantes.
- Los usuarios de un ascensor solicitan ir a pisos más bajos secuencialmente, y el ascensor los deja uno por uno en sus destinos.
- Los usuarios del otro ascensor solicitan ir a pisos más altos secuencialmente, y el ascensor también los deja uno por uno en sus destinos.

Adjunto un video con algunas ejecuciones del test case_1, que espero sirva para ejemplificar la situación y ayudar a identificar el error:

https://github.com/user-attachments/assets/f9a2c6f5-db66-4970-9145-ba15968979f0

Saludos,
Daniel

**Comment by vice-rosas99** [comment]
en la representacion grafica puede haber un error, puesto que algunos usuarios que están en estado w y afuera del ascensor (lo que significa que no han solicitado el ascensor) se meten igual al ascensor, si el test funciona de esta misma forma, tal vez sería un error

**Comment by dedarritchon** [comment]
Hola @vice-rosas99,

Ese error no está definido en el enunciado, en la modelación se permite que los usuarios se suban o bajen de los ascensores sin haberlos pedido (como ocurre en la realidad cuando alguien ya pidió el ascensor o ya pidió ir a tu mismo piso).

Saludos,
Daniel

**Comment by vice-rosas99** [comment]
ah es que en el enunciado salía que pasan de estados en el orden 1 waiting afuera -> 2 requested afuera ->3 waiting adentro -> 4requested adentro

**Comment by dedarritchon** [comment]
Hola @vice-rosas99 ,

Entiendo la discrepancia entre esos cambios de estado y este caso. Considerémoslo como un caso borde donde los usuarios pasan de estado `wainting afuera` a `waiting adentro`. De la misma forma, se puede dar que un usuario pase de `waiting adentro` a `waiting afuera`.

Saludos,
Daniel
