### ISSUE TITLE
Problema en correr el tester 

### ISSUE THREAD

**Issue by IgnaciaGonzlez** [IIC3103-2024-02/help#11]
Hola,

Estoy intentando ejecutar el tester de la tarea 1 utilizando Docker, pero me estoy encontrando con un error de conexión. He seguido los siguientes pasos:

Descargué la imagen del tester utilizando:
```
docker pull dedarritchon/tester-tarea-1-2024-2:latest
``` 

Estoy corriendo mi API en el puerto 3000.

Luego, ejecuté el tester con el siguiente comando:
```
docker run --rm --net=host -e HOST="http://localhost:3000" dedarritchon/tester-tarea-
1-2024-2:latest
``` 
He probado mis rutas en Postman y funcionan bien. Sin embargo, recibo el siguiente error al correr el tester:
```
Running tests on host: http://localhost:3000
Running test: reset... Traceback (most recent call last):
...
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /reset (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f14ba2777f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

``` 

Lo que he intentado:

* Verifiqué que mi API esté corriendo en el puerto 3000 y que la configuración de CORS esté habilitada.
* Revisé que no haya ningún problema con el mapeo de puertos. 
* Probé con -p 3000:3000 en vez de --net=host, pero sigo recibiendo el mismo error de "Connection refused". 

Preguntas:

¿Hay algún detalle que me esté faltando en la configuración del tester o de Docker para que se pueda conectar correctamente a mi API?
¿Es necesario algún otro ajuste en mi API o en Docker para que el tester pueda hacer las peticiones correctamente?

Agradezco cualquier orientación o sugerencia que puedan ofrecer.

¡Gracias de antemano!

PD: 
Aquí está la respuesta completa

```
ignacia@LAPTOP-JLVLOVPT:~$ docker run --rm --net=host -e HOST="https://localhost:3000" dedarritchon/tester-tarea
-1-2024-2:latest
Running tests on host: https://localhost:3000
Running test: reset... Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fdf3adc77f0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /reset (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdf3adc77f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/tester.py", line 47, in run_tests
    self.testCase.setUp()
  File "/app/tests.py", line 208, in setUp
    self.reset()
  File "/app/tests.py", line 182, in reset
    response = self._post(
  File "/app/tests.py", line 1416, in _post
    response = requests.post(
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /reset (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdf3adc77f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
 (0.012932s)
Running test: get_levels... Please fix reset endpoint first (4.1e-05s)
Running test: create_elevator... Please fix reset endpoint first (6e-06s)
Running test: get_elevator... Please fix reset endpoint first (3e-06s)
Running test: open_elevator_doors... Please fix reset endpoint first (5.4e-05s)
Running test: close_elevator_doors... Please fix reset endpoint first (0.000431s)
Running test: user_request_elevator... Please fix reset endpoint first (0.000376s)
Running test: board_elevator... Please fix reset endpoint first (0.000681s)
Running test: move_elevator... Please fix reset endpoint first (1e-05s)
Running test: exit_elevator... Please fix reset endpoint first (3e-06s)
Running test: case_1... Please fix reset endpoint first (3e-06s)
Running test: case_2... Please fix reset endpoint first (3e-06s)
Running test: case_3... Please fix reset endpoint first (3e-06s)

```

**Comment by sawiiii** [comment]
Tengo la misma duda y problema

**Comment by VicenteSaldana** [comment]
Yo tenía ese problema y me corre usando: docker run --rm --net=host -e HOST="http://host.docker.internal:8000" dedarritchon/tester-tarea-1-2024-2:latest

Por si te sirve (yo uso el puerto 8000)

**Comment by IgnaciaGonzlez** [comment]
Creo que ya encontré el problema. 

Al parecer la API tiene que estar dockerizada para que el tester se pueda conectar. Yo antes intentaba testarla corriendo la API directamente sin Docker. 

Ya dockerizada la API, incluso me funcionó con el mismo comando:
`docker run --rm --net=host -e HOST="http://localhost:3000" dedarritchon/tester-tarea-
1-2024-2:latest`

De todas formas, gracias @VicenteSaldana por el comentario!

**Comment by saravialu** [comment]
Hola! A mi me está pasando un problema parecido y no he logrado solucionarlo con lo que han propuesto. Ya probé dockerizándola y con varias formas de correr el tester, pero sigo con el mismo error. 
Si alguno sabe o le pasó lo mismo y lo solucionó le agradecería mucho la ayuda!
Gracias!!


El error:


Running tests on host: http://localhost:3000
Running test: reset... Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/tester.py", line 47, in run_tests
    self.testCase.setUp()
  File "/app/tests.py", line 208, in setUp
    self.reset()
  File "/app/tests.py", line 193, in reset
    self.assertOkAndExpectedBody(response, [])
  File "/app/tests.py", line 1409, in assertOkAndExpectedBody
    self.assert_matches_expected(response, expected)
  File "/app/tests.py", line 121, in assert_matches_expected
    response_body = response.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 (0.121283s)
Running test: get_levels... Please fix reset endpoint first (6.3e-05s)
Running test: create_elevator... Please fix reset endpoint first (1.3e-05s)
Running test: get_elevator... Please fix reset endpoint first (8e-06s)
Running test: open_elevator_doors... Please fix reset endpoint first (1e-05s)
Running test: close_elevator_doors... Please fix reset endpoint first (9e-06s)
Running test: user_request_elevator... Please fix reset endpoint first (1.2e-05s)
Running test: board_elevator... Please fix reset endpoint first (1.1e-05s)
Running test: move_elevator... Please fix reset endpoint first (9e-06s)
Running test: exit_elevator... Please fix reset endpoint first (7e-06s)
Running test: case_1... Please fix reset endpoint first (9e-06s)
Running test: case_2... Please fix reset endpoint first (1.2e-05s)
Running test: case_3... Please fix reset endpoint first (7e-06s)

**Comment by dedarritchon** [comment]
Hola @saravialu ,

Por lo visto, tu API está retornando una respuesta que no está en formato json, por ejemplo podría estar retornando en formato test/html. Revisa como retornar la respuesta con content-type application/json en tu framework.

Saludos,
Daniel

**Comment by saravialu** [comment]
Muchas gracias! Ahi logré correr al menos el primer test.
Sara
________________________________
De: Daniel Darritchon ***@***.***>
Enviado: miércoles, 4 de septiembre de 2024 10:23
Para: IIC3103-2024-02/help ***@***.***>
Cc: Sara Vial Undurraga ***@***.***>; Mention ***@***.***>
Asunto: Re: [IIC3103-2024-02/help] Problema en correr el tester (Issue #11)


Hola @saravialu<https://github.com/saravialu> ,

Por lo visto, tu API está retornando una respuesta que no está en formato json, por ejemplo podría estar retornando en formato test/html. Revisa como retornar la respuesta con content-type application/json en tu framework.

Saludos,
Daniel
