### ISSUE TITLE
Problema con test board_elevator

### ISSUE THREAD

**Issue by mguzman20** [IIC3103-2024-02/help#12]
![image](https://github.com/user-attachments/assets/ba77e488-af68-446e-a0f7-ba42c1aa8d21)

Estoy teniendo ese error en el tester y el objeto que estoy entregando es el siguiente:

![image](https://github.com/user-attachments/assets/7de096ad-c03c-4241-91e2-53b054a6ceb9)
(es solo una referencia de como es el objeto que devolveria)

Cual es el error?

**Comment by dedarritchon** [comment]
Hola @mguzman20 ,

Al parecer estás retornando los usuarios como string en vez de como objeto, prueba reviando el output real de tu API, ya que según el log del error, los usuarios que estás retornando son un string, por ej. puede que esté retornando algo así: ["usuario"] o ['{"id": "1", ...}']

Saludos,
Daniel

**Comment by mguzman20** [comment]
Hola, no he podido arreglar este error, me di cuenta que me falla en el endpoint get /levels/:id y esto es lo que retorna el endpoint.

![image](https://github.com/user-attachments/assets/34499ddc-b4e6-409d-8f45-6f84c8ed5135)
Esta bien el formato? 
En todos los enpoint tengo que devolver a los usuarios asi? o Funciona con una lista de ids?
