### ISSUE TITLE
Error con función para llamar ascensor 

### ISSUE THREAD

**Issue by clementestreeter** [IIC3103-2024-02/help#13]
![image](https://github.com/user-attachments/assets/ec1cdd00-9994-4c7a-ae5a-08b7e4d483b4)

Holaaa
En el enunciado de la tarea, sale que la ruta para el endpoint para llamar al ascensor es /levels/:level_id/request, pero he visto que en los test ocupan /levels/:level_id/requests (con la s al final). 
Cual debemos ocupar?
Gracias!!!

**Comment by dedarritchon** [comment]
Hola @clementestreeter ,

Se trata de un erro de tipeo del enunciado, usaremos `/requests` en plural (siguiendo el estándar REST).

Saludos,
Daniel

**Comment by Mamunoz42** [comment]
Este tipo de errores tal vez se puede subir como anuncios en canvas para que todos puedan enterarse, entiendo que deberíamos ver las issues, pero creo que es importante actualizar sobre estos temas al alumnado 😄
