### ISSUE TITLE
Problema con prioridad del ascensor.

### ISSUE THREAD

**Issue by d0dzv** [IIC3103-2024-02/help#14]
Hola!
He estado varios días probando y aún no tengo clara la prioridad que debe tener el ascensor, ya que leyendo el enunciado no soy capaz de entenderlo 😔. Hasta el momento lo tengo implementado de forma que:
1. Vaya a la petición más antigua.
2. Si existe un desplazamiento de camino, lo lleve a cabo. Por ejemplo, si estoy yendo del piso 8 al 1, y en el camino sube alguien que va del 4 al 2, lo recoja y lo deje.
3. Al terminar el recorrido, tome como prioridad la petición más antigua y volver al punto 1.

He probado de varias maneras, pero esto es lo que más me ha servido llegando hasta el test 1 donde me sale el siguiente error.

```
Running test: case_1... Test Failed: {"reason": "Expected 400, got 200. incorrect level (should go to id=16 users=[User(id='user_4', destination=-1, weight=60, status='waiting', request_timestamp=None, board_timestamp=None), User(id='user_5', destination=-1, weight=74, status='waiting', request_timestamp=None, board_timestamp=None), User(id='user_6', destination=-1, weight=69, status='waiting', request_timestamp=None, board_timestamp=None), User(id='user_7', destination=-1, weight=84, status='waiting', request_timestamp=None, board_timestamp=None), User(id='user_8', destination=-1, weight=67, status='waiting', request_timestamp=None, board_timestamp=None), User(id='user_9', destination=-1, weight=63, status='waiting', request_timestamp=None, board_timestamp=None), User(id='user_10', destination=-1, weight=69, status='waiting', request_timestamp=None, board_timestamp=None)])", "request": {"method": "PATCH", "url": "http://host.docker.internal:8000/elevators/elevator_3", "body": {"level": 16}}, "response": {"status": 200, "body": {"id": "elevator_3", "level": 16, "max_weight": 1763, "doors": "closed", "users": [], "request_queue": []}}, "expected": {"status": 400, "body": {"error": "mensaje de error (no relevante)"}}} (0.229156s)
```

De antemano muchas gracias.

**Comment by dedarritchon** [comment]
Hola @d0dzv,

La lógica que mencionas parece correcta. Al parecer hay un error en el log del tester que no permite debuggear correctamente esta parte, asique lo estamos revisando ahora para mejorar ese log.

Saludos,
Daniel

**Comment by dedarritchon** [comment]
Hola @d0dzv,

He actualizado el mensaje de error en el tester. Simplemente necesitas volver a descargar la imagen del tester utilizando `docker pull ....`

En cuanto al caso 1, lo que se está probando es lo siguiente:

- Se crean varios usuarios en un nivel específico.
- Uno de los usuarios solicita un ascensor.
- Se crea un ascensor que sube al nivel para recoger a los usuarios hasta que alcanza su capacidad máxima.
- Los usuarios que no pudieron subir solicitan el ascensor nuevamente.
- Se crea un segundo ascensor que sube para recoger a los usuarios restantes.
- Los usuarios de un ascensor solicitan ir a pisos más bajos secuencialmente, y el ascensor los deja uno por uno en sus destinos.
- Los usuarios del otro ascensor solicitan ir a pisos más altos secuencialmente, y el ascensor también los deja uno por uno en sus destinos.

Adjunto un video con algunas ejecuciones del test case_1, que espero sirva para ejemplificar la situación y ayudar a identificar el error:

https://github.com/user-attachments/assets/f9a2c6f5-db66-4970-9145-ba15968979f0

Saludos,
Daniel

**Comment by dedarritchon** [comment]
Reabro issue para darle visibilidad
