### ISSUE TITLE
Posible error del tester

### ISSUE THREAD

**Issue by CristobalGirardi** [IIC3103-2024-02/help#15]
Hola, me aparecio este error:
`Running test: board_elevator... Test Failed: {"reason": "Expected 200, got 400", "request": {"method": "PUT", "url": "http://host.docker.internal:8000/elevators/1/users/1", "body": {}}, "response": {"status": 400, "body": {"error": "User 1 is not requested"}}, "expected": {"status": 200}} (0.153899s)`

Que es cuando intenta poner a un usuario en el ascensor pero esta con status de "waiting". Sin embargo, viendo el log nunca hacen el request del llamado del ascensor, por lo que nunca cambia el status del usuario de "waiting" a "requested" y no se puede subir al ascensor.

Aqui esta el log:
`"POST /reset HTTP/1.1" 200 -`
`"GET /elevators HTTP/1.1" 200 -`
`"POST /elevators HTTP/1.1" 201 -`
`"POST /elevators HTTP/1.1" 201 -`
`"POST /elevators HTTP/1.1" 201 -`
`"POST /elevators HTTP/1.1" 201 -`
`"POST /users HTTP/1.1" 201 -`
`"PUT /elevators/1/users/1 HTTP/1.1" 400 -`
`"PATCH /elevators/1 HTTP/1.1" 200 -`
`"GET /elevators/1 HTTP/1.1" 200 -`
`"PUT /elevators/1/users/1 HTTP/1.1" 400 -` 

No se si yo estaré mal, asi si que si es asi porfavor digame. Saludos.

**Comment by dedarritchon** [comment]
Hola @CristobalGirardi,

No está definido ese error en el enunciado. Es algo que se consideró y se tomó como desición no tener este error para que el comportamiento sea más realista, ya que en la vida real las personas igual toman decisiones irracionales o se suben al ascensor sin haberlo pedido, por ejemplo si alguien más lo pidió por ellos.

Saludos,
Daniel
