### ISSUE TITLE
Excepction en Tester

### ISSUE THREAD

**Issue by anibalriveros** [IIC3103-2024-02/help#16]
Al momento de correr el tester, me aparece esta excepcion. El problema es que no se como encontrar el error, ya que no me entrega muchos detalles. Aquí dejo lo que me devuelve el tester
```

Running test: board_elevator... Traceback (most recent call last):
  File "/app/tester.py", line 49, in  #run_tests
    test()
  File "/app/tests.py", line 470, in board_elevator
    self.assertFalse(user_in_level, reason=f"user {user_id} should not be in level")
  File "/app/tests.py", line 1405, in assertFalse
    raise Exception(f"{a} is not False. {reason}")
Exception: True is not False. user 28c79127-850b-422a-a518-4ccdae59bc54 should not be in level
 (0.029284s)
```

**Comment by dedarritchon** [comment]
Hola @anibalriveros,

El problema indica que el usuario 2`8c79127-850b-422a-a518-4ccdae59bc54` no debería estar en el piso, ya que en un request anterior se subió a un ascensor (por lo que ahora está adentro del ascensor, no en el piso).

Saludos,
Daniel
