### ISSUE TITLE
Puntuacion Tarea

### ISSUE THREAD

**Issue by benjabercovich** [IIC3103-2024-02/help#19]
Buenas, tengo una duda. En el enunciado no se menciona como se divide la puntuación de la tarea. En el tester hay 10 tests de endpoints y 3 test cases generales. Cada test vale 1 punto? Es decir, con los endpoints bien son 10/13 puntos, o como funciona?

Gracias!

**Comment by dedarritchon** [comment]
Hola @benjabercovich,

No está definido, pero dado que los 3 últimos tests dado que son más complejos, podrían tener asociado más puntaje (ej. 2 pts cada uno de los últimos 3 tests).

Saludos,
Daniel
