### ISSUE TITLE
Duda con rutas Mover ascensor y Abrir / cerrar puertas del ascensor

### ISSUE THREAD

**Issue by VicenteSaldana** [IIC3103-2024-02/help#2]
Está bien que estas dos rutas sean las mismas?
![image](https://github.com/user-attachments/assets/bcd72b22-e094-4f2f-abdd-53c6cf3f123b)
![image](https://github.com/user-attachments/assets/a766b528-f18c-40a5-9c92-c9eebfdc1222)

Para saber si debo manejar ambos casos en la misma ruta o si deberían ser distintas (dado que la primera tiene un error 400 en caso de no estar el parámetro level pero la segunda no tiene dicho parámetro)

**Comment by Francescorodriguezg** [comment]
Hola Vicente

Efectivamente está bien. El request body es distinto, con eso basta para hacer el manejo requerido.
Cualquier cosa me avisas

Saludos
