### ISSUE TITLE
Duda Usuario llama alascensor desde un piso

### ISSUE THREAD

**Issue by vice-rosas99** [IIC3103-2024-02/help#20]
en la descripción del método sale que el user id debe ser válido, pero el user id es un string, dependiendo de la implementación puede tener distintos largos. Los ejemplos que dan como user_id invalidos son "hola", "[]", etc.
Como se diferencia un string valido de uno inválido?, estoy generando los ids por medio de una librería.

**Comment by dedarritchon** [comment]
Hola @vice-rosas99,

La única forma en la que se podría dar ese caso es cuando se envía el id de usuario dentro del body con un tipo inválido (no un string), por ejemplo un diccionario o lista, pero propiamente como lista `[]` o dict `{}`, no como un string de una lista "[]" o dict "{}", que sí serían string y ids válidos.

Saludos,
Daniel

**Comment by vice-rosas99** [comment]
ok perfecto, gracias
