### ISSUE TITLE
Not JSON serializable

### ISSUE THREAD

**Issue by robertoorrego** [IIC3103-2024-02/help#21]
Hola! Me di cuenta ayer que actualizaron el tester para solucionar el error de los del test case 1. Estaba pasando todos los test (no los test case) sin ningún problema. Ahora hice pull a la version nueva, no hice ningún cambio y me falla el test user_request_elevator.
El error: TypeError: Object of type Level is not JSON serializable

He comentado y desconectado todo mi código, endpoint por endpoint y no logro solucionarlo. Ni logro saber cual es el endpoint que gatilla el error. Adjunto imagen del error completo.

Agradezco todo tipo de ayuda.

![Captura de pantalla 2024-09-03 a la(s) 6 44 54 a  m](https://github.com/user-attachments/assets/c5be7588-bbcf-4b5f-a633-299c33e1adbc)

**Comment by dedarritchon** [comment]
Hola @robertoorrego ,

Probablemente al crear los ascensores estás retornando dentro del ascensor un objeto tipo Level en vez de un entero, ya que el tester usa esa respuesta para crear los ascensores que usa en el test, puedes revisar?

Saludos,
Daniel
