### ISSUE TITLE
Problema con test exit_elevator: elevator should not have users

### ISSUE THREAD

**Issue by Maxi1805** [IIC3103-2024-02/help#22]
Hola, tengo una duda con el test de exit_elevator. Cuando lo ejecuto me dice el siguiente mensaje de error.

![image](https://github.com/user-attachments/assets/0585b974-a8e8-4c16-8720-be493e878afb)

El tema es que empecé a ver cuales son las request que se mandan y no hay ningún delete con la ruta para /elevators/:elevator_id/users/:user_id. 

![image](https://github.com/user-attachments/assets/fb8dde63-fc84-4fa1-9271-4a011da72fdc)

Entonces no entiendo muy bien porque me tira ese mensaje, porque no recuerdo que haya otro método para que el elevador se haya quedado sin usuarios.

Gracias de antemano.

**Comment by dedarritchon** [comment]
Hola @Maxi1805 ,

Revisando el código del tester, el usuario debe tener como destino el piso donde está el ascensor en ese momento:

![image](https://github.com/user-attachments/assets/d9de1822-fd31-42ec-a694-69beb2c15a78)

Lo más probable es que en tu caso el usuario no tenga el valor de destination correcto y por eso "no se está bajando" (no se está haciendo el request DELETE porque nunca entra en esa condición `if user["destination"] == updated_elevator_info["level"]:`).

Saludos,
Daniel
