### ISSUE TITLE
Error en user_request_elevator

### ISSUE THREAD

**Issue by masoto22** [IIC3103-2024-02/help#23]
Hola! 

Me aparece este error en el tester 
  File "/app/tests.py", line 400, in user_requests_elevator
    self.assertEqual(len(updated_level_info["users"]), 1, reason="level should have 1 user")
  File "/app/tests.py", line 1397, in assertEqual
    raise Exception(f"{a} != {b}. {reason}")
Exception: 0 != 1. level should have 1 user
 (0.026557s)

y no entiendo la razón, ya que verifiqué con postman los users antes y después de un post/levels/level_id/requests en el nivel donde se pide un elevator y me aparece correctamente 1 user, no sé por qué podría ser que el test no detecta el usuario en la lista de users :( llevo mucho rato debuggeando el error y aún no encuentro qué podría ser

**Comment by masoto22** [comment]
Lo que igual me parece raro es que en la powershell donde estoy corriendo mi API me sale hasta ese endpoint ejecutado 
![image](https://github.com/user-attachments/assets/8592e74b-bf91-47b4-ad9e-2ed8337bb2af)
No me aparece que llame correctamente a post/levels/1/requests

Cuál podría ser el problema?

**Comment by dedarritchon** [comment]
Hola @masoto22 ,

En el test, simplemente se crea un usuario en un nivel, se obtiene el nivel, y se verifica que esté el usuario dentro del nivel:

![image](https://github.com/user-attachments/assets/2e1ae699-f4be-40e1-8f18-366cf009326d)

Efectivamente no se realiza el request POST /levels/1/requests en este test. Pero de igual forma, el usuario debería estar en el piso en estado waiting afuera.

Saludos,
Daniel

**Comment by masoto22** [comment]
Gracias profesor! Al final sí pude solucionarlo
