### ISSUE TITLE
Corrección de Tarea en caso que imagen falle

### ISSUE THREAD

**Issue by vice-rosas99** [IIC3103-2024-02/help#25]
hola, estoy teniendo un problema, por alguna razón puedo ejecutar la imagen en local (docker pone que esta corriendo) pero cuando intento hacer solicitudes o correr el tester sale conection refused, si en cambio corro el archivo main.py si resulta. Viendo que no voy a poder alcanzar a corregir eso, se corrige tambien el repositorio en git hub? 
![Captura de pantalla 2024-09-04 132607](https://github.com/user-attachments/assets/08987cb1-19bd-4f08-a875-412a9d2c740c)
![Captura de pantalla 2024-09-04 132629](https://github.com/user-attachments/assets/4693cd86-ad7a-419f-9c42-58c08e7ac79e)
![image](https://github.com/user-attachments/assets/a586f1cc-e906-4ff5-b363-8de096bea868)

en el dockerfile lo tengo asi:
![image](https://github.com/user-attachments/assets/dd00c533-f737-4d23-9f99-fe25f38f6eb5)

funciona si corro el archivo main.py sin docker en todo caso, veo que todo esta en el puerto 8000, debe ser algo de docker con sus contenedores de ejecución

**Comment by dedarritchon** [comment]
Hola @vice-rosas99,

Las correcciones que tengan dificultades se verán en la recorrección de la tarea,

Saludos,
Daniel
