### ISSUE TITLE
Error en exit_elevator: "elevator should have users"

### ISSUE THREAD

**Issue by pascualferrer** [IIC3103-2024-02/help#26]
Estoy teniendo el siguiente error por el cual me parece que no se logra ejecutar el tester de exit_elevator:
File "/app/tester.py", line 52, in run_tests
    test()
  File "/app/tests.py", line 579, in exit_elevator
    self.assertTrue(len(updated_elevator_info["users"]) > 0, reason="elevator should have users")
  File "/app/tests.py", line 1401, in assertTrue
    raise Exception(f"{a} is not True. {reason}")
Exception: False is not True. elevator should have users
 (0.073548s)
 
 Por lo que entiendo se espera que hayan usuarios en el ascensor para poder ejecutar el tester y que se baje un usuario. No entiendo por qué el ascensor no tendría usuarios si el test en el que se suben los usuarios salió todo OK. Muchas gracias.

**Comment by pascualferrer** [comment]
PLS!! UP.

No he podido solucionarlo y no entiendo por qué pasa.

**Comment by FrancoBrice** [comment]
Tengo el mismo error

**Comment by dedarritchon** [comment]
Hola @pascualferrer, @FrancoBrice ,

Al principio del test, luego de haber movido el ascensor, este debería tener un usuario adentro. Esto quiere decir, que al hacer un GET del ascensor, dentro de la respuesta debería venir una lista de los usuarios dentro del ascensor, que no debería ser vacía, puesto que hay un usuario adentro.

En su caso, sus apis están retornando una lista vacía como si no hubieran usuarios dentro del ascensor, cuando en realidad (por los requests anteriores) sí hay un usuario adentro (que posteriormente se va a bajar del ascensor).

Saludos,
Daniel
