### ISSUE TITLE
Duda sobre Docker y db

### ISSUE THREAD

**Issue by mguzman20** [IIC3103-2024-02/help#3]
Tengo una duda, ahora mismo estoy ocupando mi base de datos local, pero para entregar la tarea hay que generar una imagen de un contenedor de docker. La db deberia ir en un contenedor distinto? y luego agruparlos con docker-compose? 

Aun no comprendo bien como se utiliza DockerHub y como deberiamos utilizar docker para la entrega.

**Comment by terelopezc** [comment]
Hola! @mguzman20 
Esta semana se va a hacer una ayudantía para mostrar cómo se realiza la entrega y todo el funcionamiento de Docker.
