### ISSUE TITLE
Duda solicitud de inventario, con capacidad limitada

### ISSUE THREAD

**Issue by Kevinnevik** [IIC3103-2024-02/help#30]
Hola, tengo las siguientes dudas:

1) quisiera saber si es que solicito 80 vasos, pero mi bodega checkIn, solo tiene capacidad disponible de 60, entonces como se produce el movimiento de inventario, se debe almacenar 60 en el checkIn y 20 en el Buffer o se debe almacenar 80 en el buffer, sin que haya una adición de inventario en checkIn.

2) Es necesario utilizar bases de datos, o se pueden utilizar clases de python.

**Comment by dedarritchon** [comment]
Hola @Kevinnevik ,

Respondiendo las preguntas:

1. Si solicitas 80 vasos, y tu bodega de check in solo tiene capacidad de 60, llegarán 60 vasos a la bodega de check-in, y automáticamente los 02 restantes serán enviados a la bodega buffer, esto es algo que se hará automáticamente, no debes hacer nada adicional para que ocurra.

2. Es recomendable trabajar con bases de datos, los procesos y objetivos del proyecto serán más complejos en cada entrega, por lo que trabajar solo con objetos en memoria puede que no sea suficiente para cumplirlos (por ejemplo, qué pasa si se cae el servidor del grupo?) tienen que pensar en un sistema robusto que sea capaz de retomar el proceso ante alguna eventualidad.

Saludos,
Daniel
