### ISSUE TITLE
Tiempos para solicitar productos

### ISSUE THREAD

**Issue by Kevinnevik** [IIC3103-2024-02/help#31]
Quería consultar si es que existe la posibilidad que reduzcan los tiempos para solicitar productos, dado que estamos tratando de testear el proyecto que hemos estado realizando y se nos dificulta, que un pedido se demore 1 hora.

**Comment by dedarritchon** [comment]
Hola @Kevinnevik ,

Se reducirán los tiempos de producción en el ambiente de desarrollo a la mitad del tiempo normal. Confirmo por acá cuando esté desplegado.

Saludos,
Daniel

**Comment by arturokunder** [comment]
@Kevinnevik se cambió a la mitad del tiempo normal en ambiente de desarrollo.
