### ISSUE TITLE
Duda Entrega

### ISSUE THREAD

**Issue by Kevinnevik** [IIC3103-2024-02/help#32]
Tengo una duda, debemos llegar el 26 de septiembre con los productos ya elaborados, o el 26 recién comienzan a enviar los pedidos.

**Comment by dedarritchon** [comment]
Hola @Kevinnevik,

Para esta entrega, deberían tener los productos ya elaborados antes de la fecha de entrega, ya que las métricas serán evaluadas el 26 de septiembre a las 18:00.

Saludos,
Daniel
