### ISSUE TITLE
[Proyecto] Duda con métrica pedidos recibidos por hora

### ISSUE THREAD

**Issue by Mamunoz42** [IIC3103-2024-02/help#34]
Holaa, trabajando en la entrega me queda la duda sobre que se espera que despleguemos con la métrica **pedidos recibidos por hora**, se refiere a que mostremos los el número de pedidos que por ejemplo se han hecho entre **_x hora_** e **_y hora_**? O solamente mostrar los pedidos que se han hecho la última hora.

Saludos 😄

**Comment by dedarritchon** [comment]
Hola @Mamunoz42 ,

Dado que no se especifica en el enunciado, queda a criterio de ustedes la forma en la que se muestra esta métrica.

Generalmente se representa usando una serie de tiempo, donde el eje X es el tiempo en horas y el eje Y es la cantidad de órdenes por hora, por ejemplo:

![image](https://github.com/user-attachments/assets/d2909994-d9ad-4b97-9b90-0ba48c435186)

Saludos,
Daniel
