### ISSUE TITLE
Fabricación de productos

### ISSUE THREAD

**Issue by Kevinnevik** [IIC3103-2024-02/help#35]
Tengo dos dudas:
1. Los productos bastan con que estén producidos en la cocina, para que cuenta con la rúbrica o se debe cumplir algún criterio adicional
2. Cuál es el nombre de los atributos de los pedidos, para almacenarlos en la base de datos

**Comment by dedarritchon** [comment]
Hola @Kevinnevik ,

Respondiendo a las preguntas:

1. Basta con producirlos y que hayan sido recibidos en sus bodegas. Lo que pase después (por ejemplo si se vencen) no es relevante.
2. Por ahora no es relevante los atributos de los pedidos, la modelación deben hacerla de forma que cumpla con los objetivos, es decir, pueden definir ustedes los nombres de los atributos en su modelo y no considerar lo enviado en el request para crear las órdenes, simplemente crear la órden "a su gusto" y retornar 200 sin validar lo recibido,

Saludos,
Daniel
