### ISSUE TITLE
[Proyecto] Forma para crear productos

### ISSUE THREAD

**Issue by Mamunoz42** [IIC3103-2024-02/help#36]
Hola, estaba revisando la rúbrica y veo que los productos que debemos tener en stock deben ser producidos en base al café de grano. Mi pregunta es si debemos para esta entrega crear una lógica dentro de nuestro software que permita hacer estas acciones de preparar o solo tendríamos que hacerlo enviando requests a los EndPoints de producción de manera manual para hacerlo. No se si tal vez se podría dar más contexto de esto, ya que con el enunciado no me termina de quedar claro.
De antemano muchas gracias.

Saludos 🙌🏽

**Comment by dedarritchon** [comment]
Hola @Mamunoz42 ,

Efectivamente sería posible realizar toda la producción de manera manual, pero no es la forma recomendada de hacerlo (tomaría mucho tiempo y sería muy aburrido!). Lo esperado y lo ideal es que automaticen el proceso de producción lo más posible, por ejemplo con un script o programa que haga todos los request necesarios para crear los productos.

Saludos,
Daniel
