### ISSUE TITLE
Problemas con CSS  en Next.js al añadir extensión /web/ con nginx

### ISSUE THREAD

**Issue by IgnaciaGonzlez** [IIC3103-2024-02/help#37]
Hola,

Estoy enfrentando un problema con la configuración de CSS en mi proyecto Next.js. Al añadir la extensión /web/ en las rutas, los archivos CSS dejan de ser encontrados, lo que provoca que los estilos no se apliquen. ¿cómo puedo cambiar el PATH base para solucionar este problema?

Muchas gracias de antemano, 
Ignacia

**Comment by IgnaciaGonzlez** [comment]
Revisando la DOC de Next.js (https://nextjs.org/docs/app/api-reference/next-config-js/basePath) añadí esto:
![image](https://github.com/user-attachments/assets/72457f76-3ea1-464e-839d-d54acfe95eaa)
Pero ahora ni siquiera me encuentra para página. 
[![image](https://github.com/user-attachments/assets/fa44fa84-72bf-48e5-b874-379da341a9a0)](https://nextjs.org/docs/app/api-reference/next-config-js/basePath)

Antes por lo menos me encontraba la página, pero sin estilos.

**Comment by arturokunder** [comment]
Creo que también tienes que agregar en tu nginx que el `proxy_pass` sea a `/web`:

```
            proxy_pass URL:PORT/web;
```

**Comment by IgnaciaGonzlez** [comment]
al final agregué eso y se solucionó: 
![image](https://github.com/user-attachments/assets/769dd304-8c7e-452d-aef2-f629c571190d)

Ahora encuentra el CSS sin que se pierdan las páginas de las vistas.
