### ISSUE TITLE
Como se crean los productos?

### ISSUE THREAD

**Issue by robertoorrego** [IIC3103-2024-02/help#38]
Hola! Estoy un poco perdido en como se crean efectivamente los productos. Lo que entiendo por ahora es que tengo que tener los insumos CAFEGRANO y LECHEENTERA en la cocina y luego con el endpoint coffeeshop/products solicitar los productos Ej: CAFFELATTE.

Asumo que esto debería consumir los insumos de la cocina y retornar CAFFELATTEs.

Agradezco si me pueden aclarar la duda. Saludos!

**Comment by arturokunder** [comment]
En la api, en el listado de productos ([docs](https://dev.proyecto.2024-2.tallerdeintegracion.cl/coffeeshop/docs/#tag/Productos/paths/~1coffeeshop~1products~1available/get), [api](https://prod.proyecto.2024-2.tallerdeintegracion.cl/coffeeshop/products/available)), aparecen todas las recetas para preparar cada uno de los productos. En el caso del Cafe Latte, tiene como requerimiento:
```javascript
[
  {
    req: 1,
    sku: "LECHEENTERAPORCION"
  },
  {
    req: 1,
    sku: "CAFEMOLIDOPORCION"
  },
  {
    req: 1,
    sku: "VASOCAFE"
  }
],
```

Por lo tanto, para este producto, necesitas 1 porción de café molido, 1 porción de leche entera y 1 vaso de café. Para tener el café molido, necesitas prepararlo a partir de una unidad de café entero. Similar con la leche entera.

Cuando tengas estos tres productos en la cocina, puedes solicitar un cafe latte.
