### ISSUE TITLE
Servidor caído?

### ISSUE THREAD

**Issue by robertoorrego** [IIC3103-2024-02/help#39]
Hola! Estoy intentando probar el AUTH desde el tester de production y me retorna lo siguiente:

Code: Undocumented
Details: TypeError: Load Failed

Puede ser que este caldo el servidor de production?

**Comment by arturokunder** [comment]
@robertoorrego el server está andando sin problemas.
Si te refieres a [este tester](https://dev.proyecto.2024-2.tallerdeintegracion.cl/coffeeshop/tester/), si bien da la opción del server de prod (porque lo toma automáticamente de la [definición con openapi](https://dev.proyecto.2024-2.tallerdeintegracion.cl/coffeeshop/openapi.json) no te van a funcionar los requests apuntando a prod por temas de CORS.


En otras palabras, esto significa que el navegador te bloquea requests desde una página en dev.proyecto.2024-2.tallerdeintegracion.cl a una api en prod.proyecto.2024-2.tallerdeintegracion.cl
