### ISSUE TITLE
Solicitud extensión plazo

### ISSUE THREAD

**Issue by benjarsanchez** [IIC3103-2024-02/help#40]
Hola! Es posible extender el plazo para la entrega? 

Dado que recibimos la publicación de SKU's  que debían ser enviados el 6 de septiembre 2 semanas tarde, lo cual se entiende por la semana de receso. Pero de todos modos fue muy encima y nos atrasó el desarrollo de la entrega.

Por favor considerarlo.

Saludos,
Benjamín

**Comment by scagender** [comment]
Quiero sumar que entregar a las 18 tambien nos perjudica a algunos. Recién salgo de la pega a las 18 y pierdo todo el día.
