### ISSUE TITLE
Pedir productos

### ISSUE THREAD

**Issue by scagender** [IIC3103-2024-02/help#41]
Al recibir una orden pedimos el sku a su api y recibimos:

msg: 'Not enough materials for product. Check missing skus and quantity.'

No entendemos el por qué.

Pensamos que era porque teníamos que mover los ingredientes a la cocina, pero no nos aparece nada en ningun espacio

gracias

**Comment by scagender** [comment]
Añado más info. Somos el grupo 13, lo intentamos con CAFEGRANO y se puede ver que tenemos 280 (https://charts.mongodb.com/charts-project-0-ikdlq/public/dashboards/ce5ce7d6-ef08-4c9c-ab39-99504ebd6689)

**Comment by robertoorrego** [comment]
Les faltan los vasos! Saludos.

**Comment by scagender** [comment]
y como pedimos los vasos si altiro nos tira msg: 'Not enough materials for product. Check missing skus and quantity.'

**Comment by robertoorrego** [comment]
Igual como pidieron el cafegrano

**Comment by scagender** [comment]
Pero por eso estamos preguntando, cuando pedimos cafegrano de inmediato nos tira eso, ya ni cafegrano nos deja pedir

**Comment by scagender** [comment]
Ni cafe molido funciona

**Comment by robertoorrego** [comment]
Revisen si están pidiendo en los múltiplos que pide cada producto.

**Comment by scagender** [comment]
Lamentablemente lo hacemos

**Comment by arturokunder** [comment]
@scagender debes seguir el flujo:

1. Pedir materiales: café, vasos, leche, etc
2. Generar materiales intermedios: café molido, porciones de leche
3. Preparar café: juntas el café molido, porciones de leche y vaso, y se genera el café

En la API de productos disponibles ([link](https://prod.proyecto.2024-2.tallerdeintegracion.cl/coffeeshop/products/available), [docs](https://dev.proyecto.2024-2.tallerdeintegracion.cl/coffeeshop/docs/#tag/Productos/paths/~1coffeeshop~1products~1available/get)) aparece:
 - La receta de cada producto (ejemplo cafe latte)

```javascript
recipe: [
  {
    req: 1,
    sku: "LECHEENTERAPORCION"
  },
  {
    req: 1,
    sku: "CAFEMOLIDOPORCION"
  },
  {
    req: 1,
    sku: "VASOCAFE"
  }
],
```

 - Donde se pide cada producto:
```javascript
production: {
  at: "kitchen"
},
```

En el caso del Caffe Latte, se pide a la cocina. En este caso, todos los requerimientos de la receta deben estar en el espacio indicado con `kitchen=true` para poder generarlo.
El café en grano y la leche entera las pides al distribuidor. En estos casos, cuando pides los productos, los recibirás en el espacio indicado con `checkin=true`.
