### ISSUE TITLE
Error en API 

### ISSUE THREAD

**Issue by mguzman20** [IIC3103-2024-02/help#42]
Hola! Estamos teniendo un error al entregar una orden en /dispatch. El producto ya se encuentra en checkOut
El body de la orden es:
![image](https://github.com/user-attachments/assets/ef7e6f62-1ed8-4bdc-97ec-1afc281e457c)
Y todos los productos se crean de manera correcta y el producto ya se encuentra en checkOut, pero al momento de entregar un producto de la orden sale el siguiente error:
![image](https://github.com/user-attachments/assets/be69749f-88f4-4677-8a5e-28a6692ce852)

Que puede estar pasando? porque el error dice que no existe el id, pero es el mismo que llego a el endpoint /api/order

**Comment by arturokunder** [comment]
@mguzman20 en esta entrega **no necesitas entregar los productos**. Sólo se deben producir.

Probablemente el error se debe a que los id de órdenes que están recibiendo son del ambiente _prod_ y estás intentando realizar el envío en el ambiente _dev_

**Comment by arturokunder** [comment]
pd: con el envío estás adelantando bastante la próxima entrega, así que ese esfuerzo no está perdido en ningún caso.

**Comment by mguzman20** [comment]
Hola profesor! perdon que vuelva a insistir con esto, pero creo que existe un error al momento de entregar productos. Ya hice todos los chequeos y sabemos que los productos se encuentran en el check out. Ademas el post en coffeeshop/dispatch me tira un error 500

**Comment by arturokunder** [comment]
@mguzman20 ver #60 
Efectivamente había un error que ya corregí. Avísame si tienes otro problema!
