### ISSUE TITLE
[Proyecto] Producción de productos solicitados por enunciado.

### ISSUE THREAD

**Issue by Mamunoz42** [IIC3103-2024-02/help#43]
Holaa, que tal?

Estabamos preparandonos para hacer los pedidos pero nos surgió una duda de si en esta entrega se evaluará la optimalidad para realizar estas compras, al final solo se espera que produzcamos lo solicitado, sin importar el como llegamos a producirlo verdad?

Saludos 😄

**Comment by arturokunder** [comment]
Hola!
En esta entrega **no se evaluará la optimalidad** de la producción. Lo importante es conseguir el objetivo.
También puedes [revisar la rúbrica](https://cursos.canvas.uc.cl/courses/77948/assignments/438002) donde se detallan cada uno de los puntos de corrección.
