### ISSUE TITLE
Recepción de pedidos con atraso

### ISSUE THREAD

**Issue by robertoorrego** [IIC3103-2024-02/help#44]
Hola!

Con mi grupo no hemos logrado recibir los pedidos (grupo 8). Puedo ver en la información que habilitaron que hay cientos de pedidos creados para nosotros que no han sido aceptados ni rechazados. Si logramos arreglas la recepción de pedidos, podremos recibir esos cientos de pedidos o ya es muy tarde?

Saludos!

**Comment by arturokunder** [comment]
@robertoorrego lo importante es que los estén recibiendo para la hora de entrega. La estadística "histórica" está de manera informativa.
