### ISSUE TITLE
Numero de productos despachados

### ISSUE THREAD

**Issue by VicenteSaldana** [IIC3103-2024-02/help#45]
¿Existe una página para revisar cuántos productos hemos despachado de cada sku para esta entrega? O alguna forma de saberlo más allá de llevar la cuenta internamente

**Comment by arturokunder** [comment]
@VicenteSaldana lo puedes [revisar acá](https://charts.mongodb.com/charts-project-0-ikdlq/public/dashboards/ce5ce7d6-ef08-4c9c-ab39-99504ebd6689)

Revisa el [anuncio que envié el martes](https://cursos.canvas.uc.cl/courses/77948/discussion_topics/871682), ahí sale más explicado.
