### ISSUE TITLE
Tiempo de espera en preparacion de producto

### ISSUE THREAD

**Issue by mguzman20** [IIC3103-2024-02/help#46]
Cuando mandamos a hacer un producto se entrega el sigiente body:
![image](https://github.com/user-attachments/assets/9cc33e4f-2b53-4607-80c6-6ed07cd2fd91)
Segun la produccion de cafe expreso demora 12 segundos o 0.2 min pero segun la respuesta AviableAt - Created At son 6 segundos. Cual de los dos esta correcto?

Y si mando a producir 4 cafe expreso son 12 segundos o 12 * 4 segundos?

**Comment by arturokunder** [comment]
Hola,
Como comentó Daniel en #31 , los tiempos de generación se redujeron al 50% de lo indicado, por eso esa diferencia.
El tiempo es por solicitud de producción: si mandas a producir 4 cafe expreso, el tiempo se mantiene.
