### ISSUE TITLE
[Proyecto] Posible error en el almacenamiento de pedidos a proveedores

### ISSUE THREAD

**Issue by Mamunoz42** [IIC3103-2024-02/help#47]
Holaa, que tal?

Estabamos haciendo los pedidos necesarios para completar la entrega y me percaté que en el espacio de checkIn se almacenaron más productos del máximo, sin llevarlos al buffer como debiese ocurrir según tengo entendido. Mi pregunta es si este comportamiento es el esperado o existe algún error asociado al como se están almacenando los productos en el coffeshop.

Saludos 😄

**Comment by arturokunder** [comment]
Si, puede pasar en algunos casos bordes por temas de concurrencia en la BD.
De todas formas, una vez alcanzando ese máximo, los siguientes productos si deberían ir a `buffer`

**Comment by Mamunoz42** [comment]
Pero en ese caso nosotros deberíamos hacer que se muevan al buffer? O lo dejamos así nomas

**Comment by arturokunder** [comment]
No, los nuevos productos te llegarán automáticamente al buffer. Si ya entraron, no es necesario que lo muevas
