### ISSUE TITLE
Cantidad de vuelos simultáneos

### ISSUE THREAD

**Issue by Martinrsts** [IIC3103-2024-02/help#48]
Hola,

En la tarea 2, actualmente estoy recibiendo mensajes con un sólo vuelo, ¿Me podrían confirmar que está bien? Y si es así, ¿hay posibilidad de aumentar a al menos dos vuelos simultáneos? Me serviría para testear que la tabla de vuelos se está ordenando correctamente y que puedo recibir vuelos simultáneos.

Gracias!

**Comment by dedarritchon** [comment]
Hola @Martinrsts ,

Acabamos de subir la cantidad de vuelos simultáneos a 15.

Saludos,
Daniel
