### ISSUE TITLE
Response Body faltantes

### ISSUE THREAD

**Issue by Martinrsts** [IIC3103-2024-02/help#5]
Hola,

Hay dos llamados en los que no se especifican los response body, ¿cuáles serían para cada uno?
POST /levels/:level_id/request
PUT /elevators/:elevator_id/requests

**Comment by dedarritchon** [comment]
Hola @Martinrsts ,

No se revisará el cuerpo de la respuesta para esos requests, solo deben responder 200. En ese sentido, puedes responder cualquier respuesta, por ejemplo:

`200 {"message": "elevator requested"}`

y no habrá problema con el tester.

Saludos,
Daniel
