### ISSUE TITLE
Datos tabla de vuelos

### ISSUE THREAD

**Issue by VicenteSaldana** [IIC3103-2024-02/help#51]
Qué datos específicamente debería tener la tabla de vuelos?
La mía actualmente tiene estos:
![image](https://github.com/user-attachments/assets/5c235a11-5f0f-42dc-b070-b776ad30236f)

Es suficiente o debería tener más datos?

**Comment by dedarritchon** [comment]
Hola Vicente,

La tabla debería contener la mayor cantidad de información posible de cada vuelo. La información mínima es lo pedido en el enunciado, que sería solo mostrar la información del evento flights, sin embargo, se puede agregar más información de los vuelos cruzando información con los demás eventos (opcional).

Saludos,
Daniel
