### ISSUE TITLE
Desaparición del evento FLIGHTS

### ISSUE THREAD

**Issue by Maxi1805** [IIC3103-2024-02/help#53]
Hola,

Tenía una duda sobre la desaparición de los vuelos en el evento FLIGHTS. Se menciona que cuando uno de estos deja de aparecer, se debe eliminar toda la información relacionada. Lo que quería saber es si existe alguna otra forma de que un vuelo desaparezca que no sea avisada por alguno de los siguientes eventos: LANDING o CRASHED.

**Comment by dedarritchon** [comment]
Hola @Maxi1805 ,

Solo con esos eventos podían desaparecer los vuelos. De todas formas, solo usando la información del evento flights se podían detectar estos cambios.

Saludos,
Daniel
