### ISSUE TITLE
Duda con SFTP y sus archvivos

### ISSUE THREAD

**Issue by mguzman20** [IIC3103-2024-02/help#55]
Ya me logre conectar al servidor y leer los archivos. 
Luego de ver los archivos es necesario obtener informacion de la orden con la nueva api? o se empieza a trabajar altiro en ella? Digo esto porque la mayoria de las ordenes por sftp ya estan vencidas, entonces no tiene sentido empezar a trabajar en ellas. No se van a eliminar las ordenes vencidas del servidor?

Y otra duda en este tema, es recomendable luego de obtener la informacion de sftp hacer un post a mi api/orders para procesar la orden? y Como se puede llevar un registro de que archivos son antiguos y cuales son nuevos?

gracias

**Comment by arturokunder** [comment]
Te respondo por punto:

> No se van a eliminar las ordenes vencidas del servidor?

Las órdenes del servidor no se eliminan automáticamente. Igual puedes programar tu proceso para ir eliminando los archivos pasados.

> la mayoria de las ordenes por sftp ya estan vencidas, entonces no tiene sentido empezar a trabajar en ellas.

Sobre las órdenes vencidas, efectivamente no tiene sentido comenzar a trabajar en ellas. Te recomendaría saltarlas.

> luego de obtener la informacion de sftp hacer un post a mi api/orders para procesar la orden?

Depende de como programes tu proceso. Una ventaja de este approach es que efectivamente todas las órdenes son equivalentes: las órdenes de otros grupos como las de clientes (ftp) deberían tratarse de la misma manera.

> Como se puede llevar un registro de que archivos son antiguos y cuales son nuevos?

Puedes llevar un registro en una BD, ver fechas de creación del archivo, ir eliminando archivos, etc. Existen múltiples alternativas para esto

**Comment by IgnaciaGonzlez** [comment]
Cómo se obtiene la fecha de vencimiento? en mis archivos solo me sale esto: 
![image](https://github.com/user-attachments/assets/1a6525c7-ea9d-4e3f-90c8-5f3af976009d)
