### ISSUE TITLE
Duda con órdenes de compra de otras cafeterías

### ISSUE THREAD

**Issue by VicenteSaldana** [IIC3103-2024-02/help#56]
Hola, con mi grupo no entendemos cómo funciona el completar las órdenes de compra de otras cafeterías. Cuando tenemos su orden lista debemos hacer un dispatch solamente o debemos enviar el producto a otro grupo?

**Comment by dedarritchon** [comment]
Hola @VicenteSaldana ,

Se debe usar el endpoint de despacho, de la misma forma que con los pedidos de clientes. El endpoint de mover productos solo mueve los productos pero no aumentará la cantidad despachada de la orden.

Saludos,
Daniel
