### ISSUE TITLE
Incorrect auth entorno desarrollo

### ISSUE THREAD

**Issue by Martinrsts** [IIC3103-2024-02/help#57]
Hola!

Estamos intentando obtener el token para utilizar el sistema de gestión y el de órdenes de compra en el ambiente de desarrollo pero nos tira error de incorrect auth. ¿Puede ser que nos hayan cambiado las claves? Talvez hay algo que yo no estoy viendo en la forma de hacer la request, asique abajo escribo lo que estoy mandando.

POST
https://dev.proyecto.2024-2.tallerdeintegracion.cl/ordenes-compra/autenticar

body:
{
    "group": 2,
    "secret": "<token_enviado_por_canvas>" 
}

respuesta:
{
    "errors": [
        {
            "value": "",
            "msg": "Incorrect auth"
        }
    ]
}

**Comment by arturokunder** [comment]
Me funcionó sin problemas:

<img width="209" alt="image" src="https://github.com/user-attachments/assets/782d3233-984a-4cd8-899b-13aef2575d6b">
(imagen cortada para no mostrar el secret)

El secret de las órdenes de compra es el mismo que la bodega, pero los tokens no son intercambiables entre sistemas.
También envié las credenciales de la casilla sFTP. No se te habrá cruzado con esa clave?

**Comment by Martinrsts** [comment]
![image](https://github.com/user-attachments/assets/7fe93869-3ca2-4d47-9d62-3d1da9e4f390)

Nop, lo traté con esa clave.

**Comment by arturokunder** [comment]
Actualicé la clave en canvas. Al parecer el anunció "se comió" dos caracteres
