### ISSUE TITLE
Sistema Orden de Compra o Api

### ISSUE THREAD

**Issue by Martinrsts** [IIC3103-2024-02/help#59]
Hola,

Para manejar las órdenes de compra (vendiendo y comprando) qué debemos usar en realidad? Porque el enunciado dice que hay que avisar con la api implementada en la entrega 1, pero el sistema de orden de compras tiene su propio sistema para aceptar o rechazar. Además, que pasa si generamos una orden de compra y no avisamos por la api? o que pasa si avisamos por la api pero no generamos la orden de compra? Qué es lo que realmente cuenta?

**Comment by dedarritchon** [comment]
Hola @Martinrsts ,

Cómo hemos dicho en el curso, la fuente de la verdad es la API del cusro, es decir, lo que importa es lo que ocurra en la API de órdenes de compra, y el estado de la órden en esta.

Por ejemplo, si un grupo te acepta una orden pero no lo hace por la API, la órden realmente sigue en estado creada para todos los efectos del proyecto. De hecho si intentaran despachar con esa órden, les daría un error por no estar aceptada realmente.

Por tu lado, puedes asegurarte de la aceptación consultando con la API del curso para validar.

Saludos,
Daniel
