### ISSUE TITLE
Duda errores Usuario no encontrado en el piso

### ISSUE THREAD

**Issue by Martinrsts** [IIC3103-2024-02/help#6]
Hola,

En el llamado PUT /elevators/:elevator_id/users/:user_id, hay un error que dice "Usuario no encontrado en el piso" y otro que dice "El usuario no se encuentra en el mismo nivel que el ascensor". ¿Cuál es la diferencia? ¿De dónde se debe sacar el piso para el primer error?.

**Comment by dedarritchon** [comment]
Hola Martín,

En la práctica, siempre deben levantar el error `404 "Usuario no encontrado en el piso"`.

En el tester nunca se probará el error `"El usuario no se encuentra en el mismo nivel que el ascensor"`, por lo que pueden ignorarlo.

Saludos,
Daniel
