### ISSUE TITLE
Problema al entregar producto en orden

### ISSUE THREAD

**Issue by mguzman20** [IIC3103-2024-02/help#60]
Hola! Tenemos un problema con la API de coffeeshop al momento de entregar un producto en una orden. Haciendo un POST a /coffeeshop/dispatch. Tenemos todo el ciclo de produccion bien, se crean los productos y luego se mueven al checkOut pero al momento de entragr los productos en una orden siempre nos encontramos con un problema. 

Por ejemplo:
![image](https://github.com/user-attachments/assets/22dd92c8-02dd-4727-beb7-63d48cf55fd3)
Donde sabemos que esos id corresponden al id de un producto y recibimos un error 500

Otro ejemplo:
![image](https://github.com/user-attachments/assets/4bf49acd-2d50-4119-8eca-c4927070de37)
Donde ya estan producidos los cafe latte pero al momento de entregarlos en la orden nos tira un error 400 y investigando un poco mas en el error nos encontramos con este mensaje:
![image](https://github.com/user-attachments/assets/2f9c1c94-da44-4ee2-93ea-58a381f78b45)

Que puede estar pasando? 
Pd: Este caso es utilizando un pedido de sftp de develop y las dos api en develop.

**Comment by arturokunder** [comment]
Podrías probar de nuevo? creo que pillé el error y ya se encuentra resuelto

**Comment by mguzman20** [comment]
Pueder ser que el servidor sftp esta caido?

**Comment by arturokunder** [comment]
Está funcionanod normalmente
Puede ser que no estés cerrando tus conexiones? si no las cierras, puedes tener problemas de timeout.
Voy a reiniciarlo
