### ISSUE TITLE
Problema al hacer dispatch

### ISSUE THREAD

**Issue by VicenteSaldana** [IIC3103-2024-02/help#62]
Cuando intentamos hacer dispatch el servidor nos llega un error 500 de parte del servidor:
![image](https://github.com/user-attachments/assets/c3c2a4a2-46b3-477c-b2d5-4095725210e5)

Hablando por telegram al parecer no somos el único grupo al que le está pasando, por si nos podrían ayudar a ver qué sucede en este caso.

**Comment by arturokunder** [comment]
Ahora si debería funcionar.
Estaba el mismo error que te comenté en el correo
