### ISSUE TITLE
Habilitacion sistemas en producción

### ISSUE THREAD

**Issue by mguzman20** [IIC3103-2024-02/help#63]
Cuando se habilitan los sistemas en producción?

**Comment by Kevinnevik** [comment]
Me sumo a la pregunta

**Comment by dedarritchon** [comment]
Hola @mguzman20  @Kevinnevik ,

Disculpen la demora, se avisó por anuncio que hubo un problema de coordinación y se extendió el plazo de la entrega.

Saludos,
Daniel
