### ISSUE TITLE
Número de items por orden

### ISSUE THREAD

**Issue by Mamunoz42** [IIC3103-2024-02/help#64]
Holaaa, espero estén bien 😄

Trabajando en la entrega me surgió una duda respecto a la cantidad de items que puede tener cada orden, ya que el endpoint actualmente solo nos indica que va 1 sku, pero con la imagen de referencia que dejaron para la tabla que debe mostrar el progreso se ven más de 1 sku por orden, por lo que quería saber si para la siguiente entrega se mantendra que una orden solo puede contener 1 item, o si se pasará a soportar más de un item.

Saludos 😄

**Comment by arturokunder** [comment]
Hola! como se conversó en la clase del lunes, en cada orden sólo va 1 sku.
Disculpa por esa confusión.
