### ISSUE TITLE
Limit obtener productos en espacio

### ISSUE THREAD

**Issue by Martinrsts** [IIC3103-2024-02/help#65]
Hola,
Me tinca que esto es un error, pero talves no lo es. Cuando uno no pone el query parameter de limit en obtener productos en espacio, automáticamente retorna máximo 30. Pero el límite real es hasta 199. Eso está bien? Hay que ser explícitos en que uno quiere más de 30?

Gracias!

**Comment by arturokunder** [comment]
Es correcto, si no seteas el parámetro, usa el valor por default que es 30:

<img width="711" alt="image" src="https://github.com/user-attachments/assets/5c85b46d-a205-4215-bba5-33f5050975c1">
