### ISSUE TITLE
Tiempo de espera de productos

### ISSUE THREAD

**Issue by Maxi1805** [IIC3103-2024-02/help#66]
Hola, tengo una duda con los tiempo de espera. 

Mientras probaba mi función para producir automáticamente los productos finales, me di cuenta que se demoran más de lo que deberían. Por ejemplo, según la API el tiempo de producir cafe molido porción, es de 0.2 min o 12 segundos, sin embargo he tenido que esperar hasta 2 minutos para obtenerlos. 

Pensé que se debía a que estaba produciendo varios lotes de productos, pero en otra issue [#46](https://github.com/IIC3103-2024-02/help/issues/46) mencionan que el tiempo es por solicitud, entonces la solicitud entera debería demorar esos 12 segundos. No entiendo muy bien porque pasa esto, tuve que aumentar mucho los margenes que tenia y es un problema no saber si esos margenes van a servir en todo momento.

Espero su respuesta.

**Comment by arturokunder** [comment]
Hola,
hice un cambio para disminuir ese desfase. Ahora si debería ser mucho más cercano a lo esperado.
Los productos que se demoran muy poco, como el café molido, podrían tener un pequeño desfase, los que se demoran más, deberían andar siempre en el tiempo esperado.
