### ISSUE TITLE
Unificación de los status de las ordenes

### ISSUE THREAD

**Issue by Mamunoz42** [IIC3103-2024-02/help#67]
Hola, que tal.

Escribía esta issue para saber si es posible que se unifique el nombre del estado de aceptado a aceptada y rechazado a rechazada para que coincida con los estados que entrega el sistema de ordenes que esta poniendo a disposición el curso, quizás es parte de lo que se busca del ramo, pero si pudiesen unificarlo se agradecería.

**Comment by dedarritchon** [comment]
Hola @Mamunoz42 ,

Es normal que los identificadores no coincidan en un 100% y se debe ajustar la lógica para manejar este tipo de discrepancias.

Saludos,
Daniel
