### ISSUE TITLE
Estadísticas de la entrega

### ISSUE THREAD

**Issue by VicenteSaldana** [IIC3103-2024-02/help#68]
Buenos días, quería preguntar si existe una página para revisar las estadísticas de la entrega 2 tal cual como había una para ver las de la entrega 1. Para saber con exactitud el número de órdenes de compra y pedidos realizados por nuestro grupo para el puntaje de esta entrega.

**Comment by dedarritchon** [comment]
Hola @VicenteSaldana ,

Disculpa la demora, las páginas de estadísticas son una ayuda para el principio del proyecto pero en las entregas siguientes no están garantizadas. Con la experiencia de la primera entrega ya deberían tener su propio estado que sea suficientemente confiable para usarlo como referencia.

Saludos,
Daniel
