### ISSUE TITLE
Servidor caido Grupo 13

### ISSUE THREAD

**Issue by stefanocando** [IIC3103-2024-02/help#69]
Hola, mientras estaba corriendo la página web en nuestro servidor, se quedó pegado y se cayó. No podemos conectarnos por SSH porque tira error de timeout, hay posibilidad de que puedan reiniciar el servidor? (Grupo 13)

**Comment by dedarritchon** [comment]
Hola @stefanocando,

No era posible reiniciar los servidores durante el fin de semana, porque solo podemos pedirle al encargado durante horario laboral.

Saludos,
Daniel
