### ISSUE TITLE
Duda Ascensor superó el límite de peso

### ISSUE THREAD

**Issue by Martinrsts** [IIC3103-2024-02/help#7]
Hola,

En el error en que el usuario hace que el ascensor supere el límite de peso, ¿X kg significa la suma de los usuarios en el ascensor o la suma de los usuarios menos el límite del ascensor?

**Comment by dedarritchon** [comment]
Hola @Martinrsts ,

El valor de X en el mensaje del error no es relevante, ya que no revisaremos los mensajes de error literalmente:

> Todos los errores dentro de la API deben seguir el siguiente formato: 
> 
> { 
>     "error": string 
> } 
>  
> Es importante considerar que el texto del error en sí no se corregirá (no se hará la comparación literal de los mensajes), basta con que se levanten los errores y sus estados de error correctos en los casos que corresponda. 

Saludos,
Daniel
