### ISSUE TITLE
Error usuario baja de ascensor

### ISSUE THREAD

**Issue by Martinrsts** [IIC3103-2024-02/help#8]
Hola,

En DELETE /elevators/:elevator_id/users/:user_id, ¿se debe eliminar al usuario del programa? En tal caso, ¿cómo se diferenciaría para el error "user <user_id> already left elevator <elevator_id>" entre que el usuario dejó el ascensor o que el usuario no se encontró?

PD: la descripción del error en el enunciado dice que ese error es cuando "El usuario ya se encuentra arriba del ascensor", lo que no hace sentido.

**Comment by dedarritchon** [comment]
Hola @Martinrsts ,

Cuando el usuarios se baja del ascensor, no se elimina del programa, sino que se baja al piso en el que está el ascensor actualmente, quedando en estado `Esperando afuera del ascensor`.

La descripción del error del enunciado está mala, debería decir lo mismo que dice el error de al lado: El usuario ya bajó del ascensor (para poder bajarse debe estar dentro del ascensor).

Saludos,
Daniel
