### ISSUE TITLE
Método no mencionado en enunciado

### ISSUE THREAD

**Issue by pabloaylwin** [IIC3103-2024-02/help#9]
Hola, estoy corriendo con el tester mi API y me topo con el siguiente mensaje:

`Running test: move_elevator... Test Failed: {"reason": "Expected 200, got 404", "request": {"method": "POST", "url": "http://host.docker.internal:8000/elevators/1/requests", "body": {"user_id": "1", "level_id": 20}}, "response": {"status": 404, "body": {"detail": "Not Found"}}, "expected": {"status": 200}} (0.09834s)`

Entiendo que me está pidiendo una ruta POST /elevators/{elevator_id}/requests, pero no hay tal ruta definida en el enunciado.

**Comment by dedarritchon** [comment]
Hola @PabloAylwin ,

El enunciado tiene un pequeño error, donde dice `PUT /elevators/:elevator_id/requests` , debería decir `POST /elevators/:elevator_id/requests`.

Saludos,
Daniel
